---
- name: Gather Kubernetes Cluster Information
  hosts: all
  become: yes
  
  tasks:
    - name: Get cluster information
      kubernetes.core.k8s_cluster_info:
      register: cluster_info
    
    - name: Display cluster version
      debug:
        msg: "Kubernetes Version: {{ cluster_info.version.server.kubernetes.gitVersion }}"
    
    - name: Get all namespaces
      kubernetes.core.k8s_info:
        kind: Namespace
      register: namespaces
    
    - name: Display namespaces
      debug:
        msg: "Namespaces: {{ namespaces.resources | map(attribute='metadata.name') | list }}"
    
    - name: Get all pods across all namespaces
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: ""  # Empty string means all namespaces
      register: all_pods
    
    - name: Display pod summary
      debug:
        msg:
          - "Total Pods: {{ all_pods.resources | length }}"
          - "Pods by Namespace:"
    
    - name: Show pods by namespace
      debug:
        msg: "{{ item.metadata.namespace }}/{{ item.metadata.name }} - {{ item.status.phase }}"
      loop: "{{ all_pods.resources }}"
      loop_control:
        label: "{{ item.metadata.name }}"
    
    - name: Get all deployments
      kubernetes.core.k8s_info:
        kind: Deployment
        namespace: ""
      register: deployments
    
    - name: Display deployments
      debug:
        msg: "{{ item.metadata.namespace }}/{{ item.metadata.name }} - Replicas: {{ item.spec.replicas }}"
      loop: "{{ deployments.resources }}"
      loop_control:
        label: "{{ item.metadata.name }}"
    
    - name: Get all services
      kubernetes.core.k8s_info:
        kind: Service
        namespace: ""
      register: services
    
    - name: Display services
      debug:
        msg: "{{ item.metadata.namespace }}/{{ item.metadata.name }} - Type: {{ item.spec.type }}"
      loop: "{{ services.resources }}"
      loop_control:
        label: "{{ item.metadata.name }}"